fix v2 issues
ferib/lua-obfuscator-plugin pull request #7
Opened 2023-10-08 11:31 UTC by ferib

- Bugfix webView.html missing
- Added `npm run compile-wsl` cuz Windows has no alias for `cp` 🙃

2023-10-10 09:31 UTC, kdssoftware commented
Looks good 👌 lots of 'changes' xD

2023-10-11 10:59 UTC, kdssoftware commented on package.json
> -		"compile": "cp src/utils/*.{json,html} dist/ && tsc",
`"compile": "mkdir -p && cp src/utils/*.{json,html} dist/ && tsc",`

2023-10-11 11:00 UTC, kdssoftware requested changes
wont work without `mkdir`

2023-10-11 11:02 UTC, ferib commented
> wont work without mkdir

it will, I left a "placeholder" file in the `dist` folder 🙃

2023-10-11 11:02 UTC, merged

2023-10-11 11:05 UTC, kdssoftware commented
👌  placeholder is normally a `.gitkeep` tho. But we do want we want 🕺